name: Docker Build
on:
  push:
    branches:
      - master

env:
  RELEASE_VERSION: 5.1.5

jobs:
  omnid-docker:
    name: Build and Push images to GCP
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - uses: actions/checkout@v3

      # generate short hash to be used as image tag
      - name: Generate short hash
        id: commit-hash
        run: echo "short=$( git rev-parse --short $GITHUB_SHA )" >> $GITHUB_OUTPUT

      # setup docker binaries
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      # setup docker buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # authenticate gcp
      - id: 'auth'
        name: 'Authenticate to GCP'
        uses: 'google-github-actions/auth@v0'
        with:
          token_format: access_token
          workload_identity_provider: projects/299310520682/locations/global/workloadIdentityPools/omni-pool/providers/omni-provider
          service_account: github-actions-service-account@omni-386514.iam.gserviceaccount.com
          access_token_lifetime: 300s

      # login to gar
      - name: Login to Artifact Registry
        uses: docker/login-action@v1
        with:
          registry: us-central1-docker.pkg.dev
          username: oauth2accesstoken
          password: ${{ steps.auth.outputs.access_token }}

      - name: Add SHORT_SHA env property with commit short sha
        run: echo "SHORT_SHA=`echo ${GITHUB_SHA} | cut -c1-8`" >> $GITHUB_ENV

      - name: Tag Docker image and push to Google Artifact Registry
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./docker/Dockerfile
          cache-from: type=registry,ref=blockscout/blockscout:buildcache
          cache-to: type=registry,ref=blockscout/blockscout:buildcache,mode=max
          push: true
          tags: |
            us-central1-docker.pkg.dev/omni-386514/omni/omni-blockscout:${{ env.SHORT_SHA }}
            us-central1-docker.pkg.dev/omni-386514/omni/omni-blockscout:latest
          build-args: |
            CACHE_EXCHANGE_RATES_PERIOD=
            API_V1_READ_METHODS_DISABLED=false
            DISABLE_WEBAPP=false
            API_V1_WRITE_METHODS_DISABLED=false
            CACHE_TOTAL_GAS_USAGE_COUNTER_ENABLED=
            ADMIN_PANEL_ENABLED=false
            DECODE_NOT_A_CONTRACT_CALLS=false
            MIXPANEL_URL=
            MIXPANEL_TOKEN=
            AMPLITUDE_URL=
            AMPLITUDE_API_KEY=
            CACHE_ADDRESS_WITH_BALANCES_UPDATE_INTERVAL=
            BLOCKSCOUT_VERSION=v${{ env.RELEASE_VERSION }}-beta.+commit.${{ env.SHORT_SHA }}
            RELEASE_VERSION=${{ env.RELEASE_VERSION }}
